### ISSUE TITLE
brunei qgis readable format

### ISSUE THREAD

**Issue by justinelliotmeyers** [thewheat/brunei_map#1]
do you have this data still? tried to bring into qgis, but keeps erroring out - wonder if you have it in any other format, or shapefile format?

Thank you!

**Comment by thewheat** [comment]
Hi @justinelliotmeyers I'm afraid I'm not familiar with QGIS. What error do you get?

The gist of the information is this
- The raw data is in the `raw_data` folder https://github.com/thewheat/brunei_map/tree/master/raw_data
- And it is parsed with the parse.js file https://github.com/thewheat/brunei_map/blob/master/parse/parse.js
- And results in the output files in the `data` folder https://github.com/thewheat/brunei_map/tree/master/data

It has been so long since I've worked on this so I may not have the best context at this point in time. Do you know what forms QGIS accepts and are there any specifications for it? We may be able to figure what's wrong with it based on that info 😄

**Comment by justinelliotmeyers** [comment]
@thewheat Thanks for the quick response and follow-up! I really don't specialize in QGIS, but typically most geospatial files open fairly easily in it - so I was surprised these did not (tried from a few different directories in your repo). Do you know if the Brunei government has any other geospatial data like this? I can close out this issue as it sounds like the files worked for what you needed at the time. We can continue chat about othe Brunei data through e-mail if that works? Thanks!! Justin
